# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    environment:
      ENV: development
      SECRET_KEY: dev-secret
      DATABASE_URL: sqlite:///dev.db
      NOSTR_RELAYS: wss://relay.damus.io,wss://nos.lol
    ports:
      - "5000:5000"
    volumes:
      # mount the backend source exactly where the Dockerfile expects it
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.frontend
    environment:
      # IMPORTANT: this must be reachable from the *browser*, not from the container.
      # Since we expose backend on 5000, localhost works.
      VITE_API_BASE: http://localhost:5000
      VITE_NOSTR_RELAYS: wss://relay.damus.io,wss://nos.lol
    ports:
      - "5173:5173"
    volumes:
      # mount the frontend project at /app (matches WORKDIR in the Dockerfile)
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

