[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
line-length = 120
target-version = "py311"
# Match the Flake8 codes you're seeing
lint.select = ["E", "F", "W"]
lint.ignore = []
fix = true
